---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:

      initContainers:
      - name: migration-web
        image: {{ .Values.image.repository_1 }}:{{ .Values.image.tag_1 }}
        command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
        volumeMounts:
        - name: app
          mountPath: /app

      containers:
      - name: web
        image: {{ .Values.image.repository_2 }}:{{ .Values.image.tag_2 }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
        - containerPort: {{ .Values.pod.port }}
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/"
            port: {{ .Values.pod.port }}
        volumeMounts:
        - name: app
          mountPath: /app

      volumes:
      - name: app
        emptyDir: {}
