---
apiVersion: v1
kind: Service
metadata:
  name: clip
spec:
  selector:
    app: web
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
