---
apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    pod: web
spec:

  initContainers:
  - name: migration-web
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app

  containers:
  - name: web
    image: fred13/wep-app:latest
    volumeMounts:
    - name: app
      mountPath: /app

  volumes:
  - name: app
    emptyDir: {}

